"""
A CNL surface for DEONTIC advice — prohibition / encouragement / discouragement over ACTIONS.

This is the transient-policy surface for the card-trader domain (and any business domain): a
trader briefs the day in plain deontic English —

    don't sell                      # a strict prohibition
    today it is good to sell        # a (source-tagged) encouragement
    better not to buy               # a soft discouragement

— and each line folds to a deontic FACT about an action *class* (`sell`, `buy`), carrying the
SOURCE that asserted it. The actual REASONING over these facts — a higher-ranked source's advice
OVERRIDING a contradictory standing norm, a prohibition EXCLUDING an action class's operators — is
NOT here; it is ordinary rules in `corpus/policy.cnl` (vision §5: `overridden` is added, never
deleting the prohibition). This module is only the SURFACE that produces the facts those rules
reason over. There is no "deontic engine": `forbidden`/`encouraged` are just relations.

LEXICON AS DATA (not hardwired Python). Which phrasings mean which polarity is a DECLARED lexicon,
`<phrase> means <polarity>` (`do not means forbidden`, `it is good to means encouraged`), read by
`parse_deontic_lexicon` and turned into one recognizer FORM per phrasing by `deontic_forms` — the
same §8 "lexicon-as-data, forms-generated" discipline as `forms.relation_forms` and
`authoring.degree_grammar_forms`. `DEONTIC_LEXICON_CNL` is the DEFAULT lexicon (data); a KB extends
it just by authoring a new `means` line (`avoid means forbidden`) — no code change. The polarity
NAMES (`forbidden`/`encouraged`/`discouraged`) are the machinery contract `corpus/policy.cnl`
joins on; the author picks a phrasing and its polarity, both data.

The only genuinely-Python parts are MECHANICAL, not domain logic: contraction expansion (`don't`
-> `do not`, a tokenizer concern like `forms.normalize_lexical`'s `are` -> `is`) and the by-name
`_transfer` (the same reader `planning_kb.load_planning_kb` uses). Each line is parsed in its OWN
throwaway graph so two mentions never cross-link on the surface chain, then the recognized target
relations are transferred BY NAME through `_hub` (get-or-create), so `sell` is one shared node.

A line's SOURCE is a named authority (`today`, `standing`, `law`, `emergency`, …) — an OPEN
vocabulary: a leading word before a deontic frame is that line's source (default `standing`), and
priority among sources is authored as ordinary `A outranks B` facts. The operator classification
`?o is_a ?act` (`buy_at_shop is a buy`) is the join the machinery uses to scope a class norm to its
operators; it folds via the core `form.is_a`.

Two frames per lexicon entry (both generated by `deontic_forms`): a CLASS-level norm over an action
(`don't sell` -> `sell forbidden <source>`) and an OBJECT-scoped norm over an action + a property of
its object (`don't sell rare cards` -> `sell forbidden_for rare`), disambiguated by whether the verb
is the last token. The object-scoped norm is consumed by the exclusion rule in `corpus/policy.cnl`,
scoped by an operator's `acts_on` link and the acted-on object's property. The `forbidden_for`
naming + the dropped source are a documented Python-side convention pending reification (see
`OBJECT_SCOPE_SUFFIX`); object-scoped norms do not yet compose with the override machinery.
"""
from __future__ import annotations

from ugm.cnl.forms import FORM_RULES, tokenize
from .planning import _has_rel, _hub
from ugm.production_rule import Pat, Rule
from ugm.lowering import run_bank
from ugm.world_model import Graph

# The DEFAULT deontic lexicon, expressed as DATA (like authoring.DEGREE_CNL). Each line maps a
# surface PHRASE to a deontic POLARITY relation. A KB overrides/extends this by authoring more
# `<phrase> means <polarity>` lines — adding a phrasing is authoring, never editing this module.
DEONTIC_LEXICON_CNL = """
do not means forbidden
never means forbidden
it is good to means encouraged
better to means encouraged
better not to means discouraged
it is bad to means discouraged
"""

# Named authorities are an OPEN vocabulary (any leading word before a deontic frame); these are the
# illustrative defaults, not an allow-list. Priority among them is authored `A outranks B` facts.
DEFAULT_SOURCES: tuple[str, ...] = ("today", "standing", "law")

# Contraction expansion — a mechanical, meaning-free tokenizer concern (like `normalize_lexical`).
_CONTRACTIONS: dict[str, str] = {
    "don't": "do not", "doesn't": "does not", "didn't": "did not",
    "isn't": "is not", "won't": "will not",
    "it's": "it is", "that's": "that is",
}

# Relations copied straight through by the transfer (subject + object unchanged); the priority
# `outranks` (structural, the machinery's fixed vocabulary) and the class join `is_a`.
_PLAIN_PREDS: tuple[str, ...] = ("outranks", "is_a")
# Surface scaffolding a transfer must never mistake for a relation.
_SCAFFOLD: tuple[str, ...] = ("first", "next", "<sentence>", "<deo>")
# The priority separator keyword and the lexicon-declaration keyword.
_OUTRANKS, _MEANS = "outranks", "means"


def _normalize_deontic(line: str) -> str:
    """Expand contractions so the deontic forms see whole words (`don't` -> `do not`)."""
    return " ".join(_CONTRACTIONS.get(w.lower(), w) for w in line.split())


# ---------------------------------------------------------------------------
# The lexicon as DATA — `<phrase> means <polarity>` -> {phrase tuple: polarity}
# ---------------------------------------------------------------------------

def parse_deontic_lexicon(text: str) -> dict[tuple[str, ...], str]:
    """Read `<phrase words> means <polarity>` declarations into a `{phrase: polarity}` lexicon.

    A §8 reader (like `authoring.degree_thresholds` reading `very is 0.8`): the `means` keyword
    splits a multi-word surface phrase from its single-word polarity relation. Contraction-
    normalized first, so `don't means forbidden` and `do not means forbidden` agree. Lines without
    `means` are not declarations and are ignored here."""
    lex: dict[tuple[str, ...], str] = {}
    for raw in text.splitlines():
        line = _normalize_deontic(raw.split("#", 1)[0].strip())
        parts = line.split()
        if _MEANS not in parts:
            continue
        i = parts.index(_MEANS)
        phrase, rest = tuple(parts[:i]), parts[i + 1:]
        if phrase and len(rest) == 1:                   # `<phrase> means <one-word polarity>`
            lex[phrase] = rest[0]
    return lex


_DEFAULT_LEXICON: dict[tuple[str, ...], str] = parse_deontic_lexicon(DEONTIC_LEXICON_CNL)


# The object-scoped form emits an INTERMEDIATE `<polarity>_for` relation (`forbidden_for`,
# `encouraged_for`) — the object-scoped variant of a class polarity. The transfer then REIFIES it
# (`_mint_object_norm`) into a norm NODE carrying action/polarity/scope/SOURCE, because a
# `don't sell rare cards` norm is genuinely 4-ary and a flat triple cannot hold it. Reification
# restores the source, so object-scoped norms compose with the priority/override machinery exactly
# like class norms (see corpus/policy.cnl). The `_for` suffix is a Python-side naming convention for
# the intermediate; the reified norm's `action`/`polarity`/`scope`/`source` relations are the data
# the rules read. (A fuller move to data would also declare the reified relation NAMES in the KB.)
OBJECT_SCOPE_SUFFIX = "_for"


def _deo_form(key: str, phrase: list[str], polarity: str) -> Rule:
    """A recognizer for one lexicon entry: the surface `phrase` run followed by a single action
    verb `?v` (pinned last by the NAC) folds to `?v --polarity--> <deo>` (a placeholder object;
    the transfer substitutes the line's source). `phrase` is the contraction-expanded keyword run,
    e.g. `["do", "not"]` or `["it", "is", "good", "to"]`."""
    lhs = [Pat("?s", "first", f"{phrase[0]}?")]
    for a, b in zip(phrase, phrase[1:]):
        lhs.append(Pat(f"{a}?", "next", f"{b}?"))
    lhs.append(Pat(f"{phrase[-1]}?", "next", "?v"))
    return Rule(key=key, lhs=lhs, nac=[Pat("?v", "next", "?z")],
                rhs=[Pat("?v", polarity, "<deo>")])


def _deo_obj_form(key: str, phrase: list[str], polarity: str) -> Rule:
    """The OBJECT-SCOPED variant of `_deo_form`, generated from the SAME lexicon entry: the `phrase`
    run followed by `<verb> <adjective> <noun>` folds to `?v --<polarity>_for--> ?adj`
    (`don't sell rare cards` -> `sell forbidden_for rare`). The object is the scoping PROPERTY (the
    adjective), so the transfer copies it verbatim — no source substitution.

    Disambiguation from `_deo_form` is by whether the verb is LAST: `_deo_form`'s NAC fires when the
    verb has a successor, so `do not sell rare cards` folds ONLY here and `do not sell` folds ONLY
    there. FIRST-SLICE limit: naive single-adjective extraction — the noun after the adjective is a
    type marker (`cards`), and the middle word is taken as the property, so `don't sell my cards`
    would wrongly scope on `my` (the same n-ary NP frontier the facts/planner grammars defer)."""
    lhs = [Pat("?s", "first", f"{phrase[0]}?")]
    for a, b in zip(phrase, phrase[1:]):
        lhs.append(Pat(f"{a}?", "next", f"{b}?"))
    lhs += [Pat(f"{phrase[-1]}?", "next", "?v"), Pat("?v", "next", "?adj"),
            Pat("?adj", "next", "?noun")]
    return Rule(key=key, lhs=lhs, nac=[Pat("?noun", "next", "?z")],
                rhs=[Pat("?v", polarity + OBJECT_SCOPE_SUFFIX, "?adj")])


# The priority form `?a outranks ?b` — structural machinery vocabulary, not lexicon.
_OUTRANKS_FORM = Rule(
    key="deontic.outranks",
    lhs=[Pat("?s", "first", "?a"), Pat("?a", "next", f"{_OUTRANKS}?"),
         Pat(f"{_OUTRANKS}?", "next", "?b")],
    nac=[Pat("?b", "next", "?z")],
    rhs=[Pat("?a", _OUTRANKS, "?b")])


def deontic_forms(lexicon: dict[tuple[str, ...], str]) -> list[Rule]:
    """Generate the recognizer FORMS per lexicon entry (+ the priority `outranks` form). A §8
    form-generator over the declared lexicon DATA — exactly like `forms.relation_forms` over
    declared relations, so a newly declared phrasing parses with no code change. Each entry yields
    TWO forms from the SAME data: the class-level `_deo_form` (`don't sell`) and the object-scoped
    `_deo_obj_form` (`don't sell rare cards`), disambiguated by whether the verb is the last token."""
    forms: list[Rule] = []
    for ph, pol in sorted(lexicon.items()):
        forms.append(_deo_form(f"deontic.{pol}.{'_'.join(ph)}", list(ph), pol))
        forms.append(_deo_obj_form(f"deontic.{pol}_for.{'_'.join(ph)}", list(ph), pol))
    forms.append(_OUTRANKS_FORM)
    return forms


def _deontic_leads(lexicon: dict[tuple[str, ...], str]) -> set[str]:
    """The first word of every lexicon phrase — the words that START a deontic advice frame. A
    leading word is only read as a SOURCE when one of these follows it (data-driven, so declaring
    a new phrasing extends source detection too)."""
    return {ph[0] for ph in lexicon}


def _mint_object_norm(graph: Graph, source: str, polarity: str, action: str, scope: str) -> None:
    """Reify an OBJECT-SCOPED norm as a NODE capturing all four of (source, polarity, action,
    scope) — a flat triple cannot hold a 4-ary norm. Deterministically named, so re-asserting the
    same norm is one node (idempotent). The machinery (corpus/policy.cnl) reads the four
    `action`/`polarity`/`scope`/`source` relations; carrying the source is what lets an
    object-scoped norm compose with the priority/override machinery, exactly like a class norm."""
    n = _hub(graph, f"<norm:{source}:{polarity}:{action}:{scope}>")
    for pred, val in (("action", action), ("polarity", polarity), ("scope", scope), ("source", source)):
        if not _has_rel(graph, n, pred, val):
            graph.add_relation(n, pred, _hub(graph, val))


def _transfer(tmp: Graph, graph: Graph, source: str, polarities: set[str]) -> None:
    """Copy every recognized target relation from a parsed line's throwaway graph into `graph`, BY
    NAME through `_hub` (get-or-create). A CLASS-level deontic relation (name in `polarities`)
    becomes that relation with `source` as the object (`sell --forbidden--> standing`). An
    OBJECT-scoped `<polarity>_for` relation is REIFIED into a norm node (`_mint_object_norm`,
    carrying its source). A plain relation (`outranks`, `is_a`) copies its object verbatim.
    Add-only / idempotent."""
    obj_map = {p + OBJECT_SCOPE_SUFFIX: p for p in polarities}   # forbidden_for -> forbidden
    for r in tmp.nodes():
        pred = tmp.name(r)
        if pred not in polarities and pred not in obj_map and pred not in _PLAIN_PREDS:
            continue
        subj = next((n for n in tmp.into(r) if not tmp.is_inert(n)), None)
        if subj is None or tmp.name(subj) in _SCAFFOLD:
            continue
        sname = tmp.name(subj)
        if pred in obj_map:                             # object-scoped: reify (source, pol, act, scope)
            obj = next(iter(tmp.out(r)), None)
            if obj is None or tmp.name(obj) in _SCAFFOLD:
                continue
            _mint_object_norm(graph, source, obj_map[pred], sname, tmp.name(obj))
            continue
        if pred in polarities:
            oname = source                              # class-level: object is the line's source
        else:                                           # plain (`outranks` / `is_a`): real object
            obj = next(iter(tmp.out(r)), None)
            if obj is None or tmp.name(obj) in _SCAFFOLD:
                continue
            oname = tmp.name(obj)
        if not _has_rel(graph, _hub(graph, sname), pred, oname):
            graph.add_relation(_hub(graph, sname), pred, _hub(graph, oname))


def load_deontic(graph: Graph, text: str,
                 lexicon: dict[tuple[str, ...], str] | None = None) -> Graph:
    """Parse deontic-advice CNL (+ `A outranks B` priorities and `X is a Y` classifications) into
    `graph`; create one if none given. Each non-empty, non-`#` line is one declaration.

    The deontic lexicon is DATA: the defaults (`DEONTIC_LEXICON_CNL`), overlaid with any `<phrase>
    means <polarity>` lines in `text` (so a KB can declare a new phrasing and use it in the same
    file), overlaid with an explicit `lexicon` argument. Recognizer forms are GENERATED from that
    lexicon, so no phrasing is hardwired. A leading word before a deontic frame tags the line's
    source (default `standing`). A line no form recognizes contributes nothing (controlled
    recognition, like `load_planning_kb`)."""
    lex = dict(_DEFAULT_LEXICON)
    lex.update(parse_deontic_lexicon(text))             # inline `means` declarations extend it
    if lexicon:
        lex.update(lexicon)
    forms = FORM_RULES + deontic_forms(lex)
    leads, polarities = _deontic_leads(lex), set(lex.values())
    for raw in text.splitlines():
        line = _normalize_deontic(raw.split("#", 1)[0].strip())   # comments + contractions
        if not line or _MEANS in line.split():          # skip blanks and lexicon declarations
            continue
        words = line.split()
        # A leading word tags the source when a deontic frame word follows it (open vocabulary);
        # a frame-leading first word means no source (default `standing`), and a priority /
        # classification line keeps its first word intact (its second word is not a frame lead).
        if len(words) > 1 and words[0].lower() not in leads and words[1].lower() in leads:
            source, rest = words[0].lower(), " ".join(words[1:])
        else:
            source, rest = "standing", line
        tmp = Graph()
        tokenize(tmp, rest)
        run_bank(tmp, forms)
        _transfer(tmp, graph, source, polarities)
    return graph
